name: CI/PR

on: [push, pull_request]

env:
  DEVELOPER: 1

jobs:
  regular:
    strategy:
      matrix:
        vector:
          - jobname: osx-clang
            cc: clang
            pool: macos-latest
    env:
      CC: ${{matrix.vector.cc}}
      jobname: ${{matrix.vector.jobname}}
    runs-on: ${{matrix.vector.pool}}
    steps:
    - uses: actions/checkout@v1
    - run: ci/install-dependencies.sh
    - run: ci/run-build-and-tests.sh
      timeout-minutes: 5
    - run: ci/print-test-failures.sh
      if: failure()
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v2
      if: failure()
    - name: Upload failed tests' directories
      if: failure() && env.FAILED_TEST_ARTIFACTS != ''
      uses: actions/upload-artifact@v1
      with:
        name: failed-tests-${{matrix.vector.jobname}}
        path: ${{env.FAILED_TEST_ARTIFACTS}}
