name: CI/PR

on: [push, pull_request]

env:
  DEVELOPER: 1

jobs:
  test-cache:
    runs-on: windows-latest
    steps:
    - uses: git-for-windows/setup-git-for-windows-sdk@main
    - name: Cache a/b/c
      id: cache-abc
      uses: actions/cache@v2.1.4
      with:
        path: a/b/c
        key: abc-2113
    - name: generate a/b/c
      if: steps.cache-abc.outputs.cache-hit != 'true'
      shell: bash
      run: |
        mkdir -p a/b/c
        echo Hello >a/b/c/world.txt
    - name: /usr/bin/tar.exe is incompatible with actions/cache; move it out of the way
      if: false
      shell: bash
      run: mv /usr/bin/tar.exe /usr/bin/gtar.exe
