name: Monitor component updates

# Git for Windows is a slightly modified subset of MSYS2. Some of its
# components are maintained by Git for Windows, others by MSYS2. To help
# keeping the former up to date, this workflow monitors the Atom/RSS feeds
# and opens new tickets for each new component version.

on:
  workflow_dispatch:

env:
  CHARACTER_LIMIT: "5000"
  LAST_TIME: "48d"

jobs:
  job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        component:
          - label: pcre2
            feed: "https://en.wikipedia.org/w/index.php?title=Perl_Compatible_Regular_Expressions&feed=atom&action=history"
            contentFilter: "PCRE2 [1-9][0-9]*\\.&lt;ins"
      fail-fast: false
    steps:
      - uses: guilhem/rss-issues-action@cadba1e05ad93613180979261b7e05cee1a9b282
        with:
          feed: ${{matrix.component.feed}}
          prefix: "[New ${{matrix.component.label}} version]"
          labels: component-update
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          characterLimit: ${{ env.CHARACTER_LIMIT }}
          lastTime: ${{ env.LAST_TIME }}
          aggregate: ${{matrix.component.aggregate}}
          titleFilter: ${{matrix.component.titleFilter}}
