name: "release-test"
on:
  push:
  workflow_dispatch:
    inputs:
      release:
        description: 'Release Tag'
        required: true
        default: 'latest'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "Get release assets"
        id: get-asset
        env:
          RELEASE: ${{ github.event.inputs.release }}
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const { data } = await github.repos.getRelease({
                owner: 'microsoft', // context.repo.owner,
                repo: context.repo.repo,
                release_id: process.env.RELEASE || 'latest'
              })

            const assets = data.assets.filter(asset => asset.name.endsWith('.deb'))
            if (assets.length !== 1) {
              throw new Error(`Unexpected number of .deb assets: ${assets.length}`)
            }
            core.setOutput('name', assets[0].name)
            core.setOutput('url', assets[0].url)
      - name: DEBUG
        shell: bash
        run: |
          echo "name: ${{ steps.get-asset.outputs.name }}"
          echo "url: ${{ steps.get-asset.outputs.url }}"